# **Aula 16 - Análise de dados Parte 2: Pandas**
---

Um dos pacotes mais conhecidos, e utilizados, do Python é o **Pandas**. Com o Pandas, é possível extrair dados de diferentes tipos de arquivos para análise e montagem de dashboards, o que o torna a ferramenta perfeita para ciência de dados e inteligência artificial. É considerado um tópico praticamente esssencial para quem quer aprender Python.

O Pandas é um pacote externo. Portanto, é necessário a instalação no seu projeto usando o gerenciador **pip**, através do comando `pip install pandas`.

## Extração de dados de arquivos
---

O ideal ao fazer um trabalho que envolva análise de dados é trabalhar com os **notebooks**, ensinados na aula passada. Portanto, desta vez, iremos criar dentro da pasta do nosso projeto um arquivo com a extensão **.ipynb**. Não se esqueça de criar um **ambiente virtual _.venv_** e instalar o pacote pandas (`pip install pandas`) logo em seguida.

Para conseguirmos trabalhar com extração de dados, precisaremos de um arquivo externo. Iremos pegar para o nosso exemplo uma planilha com a extensão **.csv**. As planilhas com essa extensão estão entre as bases de dados mais utilizadas para análise de dados. Esses arquivos costumam ser gerados pelo Excel, ou exportando base de dados de Sistemas de cadastro, ou mesmo sendo gerados pos SGBD. O arquivo que iremos extrair os dados  se chama **cancelamentos.csv**, e deverá estar dentro da pasta do seu projeto.

Vamos começar improtando a biblioteca Pandas, e atribuindo um alias, e logo em seguida iremos armazenar os dados da planilha em uma variável e exibi-la na tela:

In [2]:
# importação da biblioteca pandas
import pandas as pd

# lê os dados da tabela
tabela = pd.read_csv('cancelamentos.csv')

# mostra os dados da tabela na tela
display(tabela)

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
881661,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
881662,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
881663,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
881664,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
881665,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

O comando `display()` mostra os dados em forma de tabela, como se fosse em uma planilha.